FROM python:3.12-slim

RUN apt-get update && apt-get install -y git

RUN git clone https://github.com/Nikita-Filonov/qa-automation-engineer-api-course.git /app/server

WORKDIR /app/server
RUN pip install --no-cache-dir -r requirements.txt

EXPOSE 8000

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]